### ISSUE TITLE
有些pdf的一些字体，浏览时内容会不显示

### ISSUE THREAD

**Issue by ChanQu** [FantasyLWX/AndroidMuPDF#2]
您好，有些pdf文件里面的一些字体，浏览pdf时会显示不出来，页面空白。
比如提示
cannot open /system/fonts/NotoSansCJK-Regular.ttc: 

在android5、6版本会这样。应该怎么处理？

**Comment by FantasyLWX** [comment]
这个应该是系统不含这个字体导致的，建议在APP内部自己导入使用或换种字体。
